# Generated by Django 4.2.2 on 2023-06-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gbfs_href', models.URLField()),
                ('href', models.CharField(max_length=100)),
                ('network_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bike_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='testPracticoDeveloper.bikenetwork')),
            ],
        ),
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('station_id', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('bike_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='testPracticoDeveloper.bikenetwork')),
            ],
        ),
    ]
