# Generated by Django 4.2.2 on 2023-06-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testPracticoDeveloper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikestation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('altitude', models.FloatField()),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('last_updated', models.IntegerField()),
                ('normal_bikes', models.IntegerField()),
                ('payment', models.JSONField()),
                ('payment_terminal', models.BooleanField()),
                ('renting', models.IntegerField()),
                ('returning', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('uid', models.CharField(max_length=100)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='testPracticoDeveloper.bikestation')),
            ],
        ),
    ]
