# Generated by Django 4.2.2 on 2023-06-15 04:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPracticoDeveloper', '0002_alter_bikestation_timestamp_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='station',
        ),
        migrations.RemoveField(
            model_name='location',
            name='bike_network',
        ),
        migrations.AddField(
            model_name='bikenetwork',
            name='company',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='bikenetwork',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bikenetwork',
            name='stations',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='BikeStation',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
